package com.example.ui.model

enum class AppLanguage(val code: String, val displayName: String, val flag: String) {
    MALAYALAM("ml", "മലയാളം", "🇮🇳"),
    ENGLISH("en", "English", "🌐")
}

data class AppStrings(
    val appName: String,
    val appSubtitle: String,
    val dailyProgress: String,
    val completedOfTotal: (completed: Int, total: Int) -> String,
    val motivationAllCaughtUp: String,
    val motivationHalfway: String,
    val motivationGoodMomentum: String,
    val motivationReady: String,
    val motivationNoTasks: String,
    val total: String,
    val pending: String,
    val done: String,
    val filterAll: String,
    val filterPending: String,
    val filterCompleted: String,
    val newTask: String,
    val createNewTask: String,
    val editTask: String,
    val taskTitleLabel: String,
    val taskTitlePlaceholder: String,
    val notesLabel: String,
    val notesPlaceholder: String,
    val priorityLevel: String,
    val categoryLabel: String,
    val timelineLabel: String,
    val timelinePlaceholder: String,
    val saveChanges: String,
    val addTask: String,
    val delete: String,
    val cancel: String,
    val clearCompleted: String,
    val clearCompletedDialogTitle: String,
    val clearCompletedDialogDesc: (count: Int) -> String,
    val clearAll: String,
    val undo: String,
    val taskDeletedMessage: (title: String) -> String,
    val searchPlaceholder: String,
    val searchClear: String,
    val searchToggle: String,
    val emptyNoMatching: String,
    val emptyNoMatchingDesc: String,
    val emptyListClear: String,
    val emptyListClearDesc: String,
    val emptyFilter: String,
    val emptyFilterDesc: String,
    val quickDates: List<String>,
    val priorityLow: String,
    val priorityMedium: String,
    val priorityUrgent: String,
    val categoryAll: String,
    val categoryPersonal: String,
    val categoryWork: String,
    val categoryShopping: String,
    val categoryHealth: String,
    val categoryStudy: String,
    val categoryIdeas: String
)

val MalayalamStrings = AppStrings(
    appName = "ടാസ്ക് ഫ്ലോ",
    appSubtitle = "പ്രാദേശിക & സ്വകാര്യ ടാസ്ക് മാനേജർ",
    dailyProgress = "പ്രതിദിന പുരോഗതി",
    completedOfTotal = { completed, total -> "$total ൽ $completed എണ്ണം പൂർത്തിയായി" },
    motivationAllCaughtUp = "എല്ലാ കാര്യങ്ങളും പൂർത്തിയായി! അഭിനന്ദനങ്ങൾ! 🎉",
    motivationHalfway = "പകുതിയിലധികം കഴിഞ്ഞു! മുന്നോട്ട് പോകുക! 🔥",
    motivationGoodMomentum = "നല്ല വേഗതയുണ്ട്! തുടരൂ! ⚡",
    motivationReady = "ഇന്നത്തെ ലക്ഷ്യങ്ങൾ നേടാം! തുടങ്ങാം! 💪",
    motivationNoTasks = "ടാസ്കുകൾ ഒന്നും ചേർത്തിട്ടില്ല. ഇപ്പോൾ ആരംഭിക്കൂ! 🚀",
    total = "ആകെ",
    pending = "ബാക്കി",
    done = "പൂർത്തിയായി",
    filterAll = "എല്ലാം",
    filterPending = "തീർക്കാനുള്ളവ",
    filterCompleted = "പൂർത്തിയായത്",
    newTask = "പുതിയ ടാസ്ക്",
    createNewTask = "പുതിയ ടാസ്ക് ചേർക്കുക",
    editTask = "ടാസ്ക് മാറ്റിയെഴുതുക",
    taskTitleLabel = "ടാസ്ക് തലക്കെട്ട് *",
    taskTitlePlaceholder = "എന്താണ് ചെയ്യേണ്ടത്?",
    notesLabel = "കുറിപ്പുകൾ & വിവരങ്ങൾ (വേണമെങ്കിൽ)",
    notesPlaceholder = "കൂടുതൽ വിവരങ്ങൾ, കുറിപ്പുകൾ ഇവിടെ ചേർക്കാം...",
    priorityLevel = "മുൻഗണന",
    categoryLabel = "വിഭാഗം",
    timelineLabel = "തീയതി / സമയം",
    timelinePlaceholder = "ഉദാ: ഇന്ന്, നാളെ വൈകുന്നേരം 5 മണി, അടുത്ത ആഴ്ച",
    saveChanges = "മാറ്റങ്ങൾ സേവ് ചെയ്യുക",
    addTask = "ടാസ്ക് ചേർക്കുക",
    delete = "ഡിലീറ്റ് ചെയ്യുക",
    cancel = "റദ്ദാക്കുക",
    clearCompleted = "പൂർത്തിയായവ മായ്ക്കുക",
    clearCompletedDialogTitle = "പൂർത്തിയായവ മായ്ക്കണമോ?",
    clearCompletedDialogDesc = { count -> "പൂർത്തിയായ $count ടാസ്കുകൾ ശാശ്വതമായി ഫോണിൽ നിന്ന് നീക്കം ചെയ്യപ്പെടും." },
    clearAll = "എല്ലാം മായ്ക്കുക",
    undo = "തിരിച്ചെടുക്കുക",
    taskDeletedMessage = { title -> "\"$title\" നീക്കം ചെയ്തു" },
    searchPlaceholder = "ടാസ്കുകൾ തിരയുക...",
    searchClear = "തിരച്ചിൽ മാറ്റുക",
    searchToggle = "തിരയുക",
    emptyNoMatching = "ടാസ്കുകൾ ഒന്നും കണ്ടെത്തിയില്ല",
    emptyNoMatchingDesc = "മറ്റൊരു വാക്ക് നൽകി തിരയുക അല്ലെങ്കിൽ സെർച്ച് മാറ്റുക.",
    emptyListClear = "ലിസ്റ്റിൽ ടാസ്കുകൾ ഒന്നുമില്ല!",
    emptyListClearDesc = "തുടങ്ങാൻ തയ്യാറാണോ? താഴെയുള്ള \"പുതിയ ടാസ്ക്\" ബട്ടൺ അമർത്തി നിങ്ങളുടെ പ്ലാനുകൾ കുറിക്കുക.",
    emptyFilter = "ഈ ഫിൽട്ടറിൽ ടാസ്കുകളില്ല",
    emptyFilterDesc = "മറ്റു ടാസ്കുകൾ കാണാൻ \"എല്ലാം\" തിരഞ്ഞെടുക്കുക.",
    quickDates = listOf("ഇന്ന്", "നാളെ", "ഈ ആഴ്ചാവസാനം", "അടുത്ത ആഴ്ച"),
    priorityLow = "കുറഞ്ഞത്",
    priorityMedium = "ഇടത്തരം",
    priorityUrgent = "അടിയന്തിരം",
    categoryAll = "എല്ലാം",
    categoryPersonal = "വ്യക്തിഗതം",
    categoryWork = "ജോലി",
    categoryShopping = "ഷോപ്പിംഗ്",
    categoryHealth = "ആരോഗ്യം",
    categoryStudy = "പഠനം",
    categoryIdeas = "ചിന്തകൾ"
)

val EnglishStrings = AppStrings(
    appName = "TaskFlow",
    appSubtitle = "Local & Private Task Manager",
    dailyProgress = "Daily Progress",
    completedOfTotal = { completed, total -> "$completed of $total completed" },
    motivationAllCaughtUp = "All caught up! Great job! 🎉",
    motivationHalfway = "Over halfway there! Keep flowing! 🔥",
    motivationGoodMomentum = "Good momentum! Keep going! ⚡",
    motivationReady = "Ready to conquer today? Let's do this! 💪",
    motivationNoTasks = "No tasks yet. Create one to get started! 🚀",
    total = "Total",
    pending = "Pending",
    done = "Done",
    filterAll = "All",
    filterPending = "Pending",
    filterCompleted = "Completed",
    newTask = "New Task",
    createNewTask = "Create New Task",
    editTask = "Edit Task",
    taskTitleLabel = "Task Title *",
    taskTitlePlaceholder = "What needs to be done?",
    notesLabel = "Notes & Details (optional)",
    notesPlaceholder = "Add extra context, links, or sub-points...",
    priorityLevel = "Priority Level",
    categoryLabel = "Category",
    timelineLabel = "Timeline / Due",
    timelinePlaceholder = "e.g. Today, Tomorrow 5 PM, Next Week",
    saveChanges = "Save Changes",
    addTask = "Add Task",
    delete = "Delete",
    cancel = "Cancel",
    clearCompleted = "Clear Completed Tasks",
    clearCompletedDialogTitle = "Clear Completed Tasks?",
    clearCompletedDialogDesc = { count -> "This will permanently remove $count completed tasks from your local storage." },
    clearAll = "Clear All",
    undo = "Undo",
    taskDeletedMessage = { title -> "\"$title\" deleted" },
    searchPlaceholder = "Search tasks...",
    searchClear = "Clear search",
    searchToggle = "Search Tasks",
    emptyNoMatching = "No matching tasks found",
    emptyNoMatchingDesc = "Try searching for another keyword or clear the search query.",
    emptyListClear = "Your task list is clear!",
    emptyListClearDesc = "Ready to get things done? Tap the \"New Task\" button below to start your productive flow.",
    emptyFilter = "No tasks in this filter",
    emptyFilterDesc = "Switch back to \"All\" to see your other tasks, or add a new one.",
    quickDates = listOf("Today", "Tomorrow", "This Weekend", "Next Week"),
    priorityLow = "Low",
    priorityMedium = "Medium",
    priorityUrgent = "Urgent",
    categoryAll = "All",
    categoryPersonal = "Personal",
    categoryWork = "Work",
    categoryShopping = "Shopping",
    categoryHealth = "Health",
    categoryStudy = "Study",
    categoryIdeas = "Ideas"
)
